# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flapjack}
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lindsay Holmwood"]
  s.date = %q{2011-01-11}
  s.description = %q{lapjack is highly scalable and distributed monitoring system. It understands the Nagios plugin format, and can easily be scaled from 1 server to 1000.}
  s.email = %q{lindsay@holmwood.id.au}
  s.executables = ["flapjack-benchmark", "flapjack-netsaint-parser", "flapjack-notifier", "flapjack-notifier-manager", "flapjack-populator", "flapjack-stats", "flapjack-worker", "flapjack-worker-manager", "install-flapjack-systemwide"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENCE",
     "README.md",
     "Rakefile",
     "TODO.md",
     "VERSION",
     "bin/flapjack-benchmark",
     "bin/flapjack-netsaint-parser",
     "bin/flapjack-notifier",
     "bin/flapjack-notifier-manager",
     "bin/flapjack-populator",
     "bin/flapjack-stats",
     "bin/flapjack-worker",
     "bin/flapjack-worker-manager",
     "bin/install-flapjack-systemwide",
     "doc/CONFIGURING.md",
     "doc/DEVELOPING.md",
     "doc/INSTALL.md",
     "doc/PACKAGING.md",
     "etc/default/flapjack-notifier",
     "etc/default/flapjack-workers",
     "etc/flapjack/flapjack-notifier.conf.example",
     "etc/flapjack/recipients.conf.example",
     "etc/init.d/flapjack-notifier",
     "etc/init.d/flapjack-workers",
     "features/flapjack-notifier-manager.feature",
     "features/flapjack-worker-manager.feature",
     "features/netsaint-config-converter.feature",
     "features/packaging-lintian.feature",
     "features/persistence/couch.feature",
     "features/persistence/sqlite3.feature",
     "features/persistence/steps/couch_steps.rb",
     "features/persistence/steps/generic_steps.rb",
     "features/persistence/steps/sqlite3_steps.rb",
     "features/steps/flapjack-importer_steps.rb",
     "features/steps/flapjack-netsaint-parser_steps.rb",
     "features/steps/flapjack-notifier-manager_steps.rb",
     "features/steps/flapjack-worker-manager_steps.rb",
     "features/steps/packaging-lintian_steps.rb",
     "features/support/env.rb",
     "features/support/silent_system.rb",
     "features/support/tmp/.stub",
     "flapjack.gemspec",
     "lib/flapjack/applications/notifier.rb",
     "lib/flapjack/applications/worker.rb",
     "lib/flapjack/checks/http_content",
     "lib/flapjack/checks/ping",
     "lib/flapjack/cli/notifier.rb",
     "lib/flapjack/cli/notifier_manager.rb",
     "lib/flapjack/cli/worker.rb",
     "lib/flapjack/cli/worker_manager.rb",
     "lib/flapjack/filters/any_parents_failed.rb",
     "lib/flapjack/filters/ok.rb",
     "lib/flapjack/inifile.rb",
     "lib/flapjack/notifier_engine.rb",
     "lib/flapjack/notifiers/mailer/init.rb",
     "lib/flapjack/notifiers/mailer/mailer.rb",
     "lib/flapjack/notifiers/xmpp/init.rb",
     "lib/flapjack/notifiers/xmpp/xmpp.rb",
     "lib/flapjack/patches.rb",
     "lib/flapjack/persistence/couch.rb",
     "lib/flapjack/persistence/couch/connection.rb",
     "lib/flapjack/persistence/couch/couch.rb",
     "lib/flapjack/persistence/data_mapper.rb",
     "lib/flapjack/persistence/data_mapper/data_mapper.rb",
     "lib/flapjack/persistence/data_mapper/models/check.rb",
     "lib/flapjack/persistence/data_mapper/models/check_template.rb",
     "lib/flapjack/persistence/data_mapper/models/event.rb",
     "lib/flapjack/persistence/data_mapper/models/node.rb",
     "lib/flapjack/persistence/data_mapper/models/related_check.rb",
     "lib/flapjack/persistence/sqlite3.rb",
     "lib/flapjack/persistence/sqlite3/sqlite3.rb",
     "lib/flapjack/transports/beanstalkd.rb",
     "lib/flapjack/transports/result.rb",
     "spec/check_sandbox/echo",
     "spec/check_sandbox/sandboxed_check",
     "spec/configs/flapjack-notifier-couchdb.ini",
     "spec/configs/flapjack-notifier.ini",
     "spec/configs/recipients.ini",
     "spec/helpers.rb",
     "spec/inifile_spec.rb",
     "spec/mock-notifiers/mock/init.rb",
     "spec/mock-notifiers/mock/mock.rb",
     "spec/notifier-directories/spoons/testmailer/init.rb",
     "spec/notifier_application_spec.rb",
     "spec/notifier_filters_spec.rb",
     "spec/notifier_options_multiplexer_spec.rb",
     "spec/notifier_options_spec.rb",
     "spec/notifier_spec.rb",
     "spec/notifiers/mailer_spec.rb",
     "spec/notifiers/xmpp_spec.rb",
     "spec/persistence/datamapper_spec.rb",
     "spec/persistence/mock_persistence_backend.rb",
     "spec/simple.ini",
     "spec/spec.opts",
     "spec/test-filters/blocker.rb",
     "spec/test-filters/mock.rb",
     "spec/transports/beanstalkd_spec.rb",
     "spec/transports/mock_transport.rb",
     "spec/worker_application_spec.rb",
     "spec/worker_options_spec.rb"
  ]
  s.homepage = %q{http://flapjack-project.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{a scalable and distributed monitoring system}
  s.test_files = [
    "spec/helpers.rb",
     "spec/inifile_spec.rb",
     "spec/mock-notifiers/mock/init.rb",
     "spec/mock-notifiers/mock/mock.rb",
     "spec/notifier-directories/spoons/testmailer/init.rb",
     "spec/notifier_application_spec.rb",
     "spec/notifier_filters_spec.rb",
     "spec/notifier_options_multiplexer_spec.rb",
     "spec/notifier_options_spec.rb",
     "spec/notifier_spec.rb",
     "spec/notifiers/mailer_spec.rb",
     "spec/notifiers/xmpp_spec.rb",
     "spec/persistence/datamapper_spec.rb",
     "spec/persistence/mock_persistence_backend.rb",
     "spec/test-filters/blocker.rb",
     "spec/test-filters/mock.rb",
     "spec/transports/beanstalkd_spec.rb",
     "spec/transports/mock_transport.rb",
     "spec/worker_application_spec.rb",
     "spec/worker_options_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<daemons>, ["= 1.0.10"])
      s.add_runtime_dependency(%q<beanstalk-client>, ["= 1.0.2"])
      s.add_runtime_dependency(%q<log4r>, ["= 1.1.5"])
      s.add_runtime_dependency(%q<xmpp4r>, ["= 0.5"])
      s.add_runtime_dependency(%q<tmail>, ["= 1.2.3.1"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["= 0.6.4"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, ["= 1.2.5"])
    else
      s.add_dependency(%q<daemons>, ["= 1.0.10"])
      s.add_dependency(%q<beanstalk-client>, ["= 1.0.2"])
      s.add_dependency(%q<log4r>, ["= 1.1.5"])
      s.add_dependency(%q<xmpp4r>, ["= 0.5"])
      s.add_dependency(%q<tmail>, ["= 1.2.3.1"])
      s.add_dependency(%q<yajl-ruby>, ["= 0.6.4"])
      s.add_dependency(%q<sqlite3-ruby>, ["= 1.2.5"])
    end
  else
    s.add_dependency(%q<daemons>, ["= 1.0.10"])
    s.add_dependency(%q<beanstalk-client>, ["= 1.0.2"])
    s.add_dependency(%q<log4r>, ["= 1.1.5"])
    s.add_dependency(%q<xmpp4r>, ["= 0.5"])
    s.add_dependency(%q<tmail>, ["= 1.2.3.1"])
    s.add_dependency(%q<yajl-ruby>, ["= 0.6.4"])
    s.add_dependency(%q<sqlite3-ruby>, ["= 1.2.5"])
  end
end

